routes/web.php
<?php

use App\Http\Controllers\AdminDashboardController;
use App\Http\Controllers\AthleteDashboardController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

Route::group(['middleware' => ['auth']], function () {


    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('profile', [\App\Http\Controllers\ProfileController::class, 'show'])->name('profile.show');
    Route::put('profile', [\App\Http\Controllers\ProfileController::class, 'update'])->name('profile.update');

    Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function () {
        Route::get('dashboard', [AdminDashboardController::class, 'index'])->name('admin.dashboard.index');

        Route::get('users', [UserController::class, 'index'])->name('users.index');
        Route::get('users/create', [UserController::class, 'create'])->name('users.create');
        Route::post('users', [UserController::class, 'store'])->name('users.store');
        Route::get('users/edit/{user}', [UserController::class, 'edit'])->name('users.edit');
        Route::put('users/{user}', [UserController::class, 'update'])->name('users.update');
        Route::delete('users/{user}', [UserController::class, 'destroy'])->name('users.destroy');

        Route::resource('course', CourseController::class);
    });

    Route::group(['prefix' => 'athlete', 'middleware' => ['role:athlete']], function () {

        Route::get('dashboard', [AthleteDashboardController::class, 'index'])->name('athlete.dashboard.index');
    });
});

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/courses/create.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Create Course') }}
    </x-slot>

    <div class="p-4 bg-white rounded-lg shadow-xs">
        <div class="p-5 overflow-hidden w-full rounded-lg border shadow-xs">
            <x-auth-validation-errors />
            <div class="overflow-x-auto w-full">
                <div class="flex items-center justify-center p-6 sm:p-12">
                    <div class="w-full">
                        <form method="POST" action="{{ route('course.store') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="w-full">
                                <div class="grid grid-cols-2 gap-4">
                                    <div class="my-3">
                                         <x-label for="description" :value="__('Decription')"/>
                                         <x-input name="description"
                                                 type="text"
                                                 class="block w-full"
                                                 value="{{ old('description') }}"/>
                                    </div>

                                    <div class="my-3">
                                     <x-label for="college" :value="__('College')"/>
                                     <select name="college" class="mt-1 w-full border-gray-300 rounded-md shadow-sm focus:border-primary-300 focus:ring focus:ring-primary-200 focus:ring-opacity-50 focus-within:text-primary-600">
                                        <option value="" selected disabled>-- Select College --</option>
                                        <option value="CAS">CAS</option>
                                        <option value="COED">COED</option>
                                        <option value="CME">CME</option>
                                    </select>
                                 </div>

                            </div>

                            <div class="mt-4">
                                <x-button class="block ">
                                    {{ __('Create Athlete') }}
                                </x-button>
                            </div>
                        </form>
                </div>
            </div>

        </div>

    </div>
</x-app-layout>

resources/views/courses/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Create Course') }}
    </x-slot>

    <div class="p-4 bg-white rounded-lg shadow-xs">
        <div class="p-5 overflow-hidden w-full rounded-lg border shadow-xs">
            <x-auth-validation-errors />
            <div class="overflow-x-auto w-full">
                <div class="flex items-center justify-center p-6 sm:p-12">
                    <div class="w-full">
                        <form method="POST" action="{{ route('course.update', $course) }}" enctype="multipart/form-data">
                            @method('PUT')
                            @csrf
                            <div class="w-full">
                                <div class="grid grid-cols-2 gap-4">
                                    <div class="my-3">
                                         <x-label for="description" :value="__('Decription')"/>
                                         <x-input name="description"
                                                 type="text"
                                                 class="block w-full"
                                                 value="{{ $course->description }}"/>
                                    </div>

                                    <div class="my-3">
                                     <x-label for="college" :value="__('College')"/>
                                     <select name="college" class="mt-1 w-full border-gray-300 rounded-md shadow-sm focus:border-primary-300 focus:ring focus:ring-primary-200 focus:ring-opacity-50 focus-within:text-primary-600">
                                        <option value="CAS" @if ($course->college == 'CAS') selected  @endif>CAS</option>
                                        <option value="COED" @if ($course->college == 'COED') selected  @endif>COED</option>
                                        <option value="CME" @if ($course->college == 'CME') selected  @endif>CME</option>
                                    </select>
                                 </div>

                            </div>

                            <div class="mt-4">
                                <x-button class="block ">
                                    {{ __('Create Athlete') }}
                                </x-button>
                            </div>
                        </form>
                </div>
            </div>

        </div>

    </div>
</x-app-layout>

resources/views/courses/index.blade.php
<x-app-layout>
    <x-slot name="header">
        {{ __('Users') }}
    </x-slot>

    <div class="p-4 bg-white rounded-lg shadow-xs">

        <div class="inline-flex overflow-hidden mb-4 w-full bg-white rounded-lg shadow-md">
            <div class="w-full" x-data="{ show: true }" x-show.transition.opacity.out.duration.2000ms="show" x-init="setTimeout(() => show = false, 5000)">
                <x-success-message class="w-full"/>
            </div>
        </div>

        <div class="mb-5">
            <x-a href="{{ route('course.create') }}">
                {{ __('Add Course') }}
            </x-a>
        </div>

        <div class="overflow-hidden mb-8 w-full rounded-lg border shadow-xs">
            <div class="overflow-x-auto w-full">
                <table class="w-full whitespace-no-wrap">
                    <thead>
                    <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase bg-gray-50 border-b">
                        <th class="px-4 py-3">Description</th>
                        <th class="px-4 py-3">College</th>
                        <th class="px-4 py-3 ">Action</th>
                    </tr>
                    </thead>
                    <tbody class="bg-white divide-y">
                        @foreach ($courses as $course)
                        <tr>
                            <td class="px-4 py-3 text-sm">
                                {{ $course->description }}
                            </td>

                            <td class="px-4 py-3 text-sm">
                                {{$course->college  }}
                            </td>

                            <td class="px-4 py-3 text-center">
                              <div class="flex">
                                <div class="mr-2">
                                    <a href="{{ route('course.edit', $course) }}">
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-500 text-white">
                                            Update
                                          </span>
                                       </a>
                                   </div>

                                   <div>
                                    <form action="{{ route('course.destroy', $course) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" onclick="return confirm('Are you sure?')">
                                            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-500 text-white">
                                                Delete
                                              </span>
                                        </button>
                                    </form>
                                   </div>
                              </div>

                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="px-4 py-3 text-xs font-semibold tracking-wide text-gray-500 uppercase bg-gray-50 border-t sm:grid-cols-9">
                    {{ $courses->links() }}
                </div>
        </div>

    </div>
</x-app-layout>